version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build Vite app
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - package-lock.json
            - node_modules

  test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Vitest
          command: npm test -- --run

  deploy:
    docker:
      - image: cimg/node:18.20
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI locally
          command: npm install --save-dev vercel
      - run:
          name: Disable telemetry
          command: export VERCEL_TELEMETRY=0
      - run:
          name: Deploy to Vercel (headless)
          command: npx vercel ./dist --prod --confirm --token jGCe49zfwxKCWUcIGFDgeyJ4 --scope team_ZlmHAV7mELGxNF1zu3LNFURd

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: rahmat
